within OpenHPL.Tests;
model HPModelObservSim
  inner OpenHPL.Data data;
  //HPModel hpmod;
  //HPLiniarization hpreal;
  HPLiniarizationKP hprealkp;
  import Modelica.Constants.pi;
  parameter Real H_r = 48, H_i = 23, H_p = 428.5, H_s = 120, H_d = 0.5, H_t = 5;
  parameter Real L_i = 6600, L_p = 600, L_s = 140, L_d = 600;
  parameter Real D_i = 5.8, D_p = 3, D_s = 3.4, D_d = 5.8;
  parameter Real C_v = 3.7, fD = 0.043;
  parameter Real L3 = -10;
  parameter Real L1 = 1.5;
  parameter Real x_2 = 1;
  parameter Real L1uweight = 0;
  Real u;
  Real x1, x3;
  Real A_i = D_i ^ 2 * pi / 4, A_p = D_p ^ 2 * pi / 4, A_s = D_s ^ 2 * pi / 4, A_d = D_d ^ 2 * pi / 4;
  Real cos_theta_i = H_i / L_i, cos_theta_p = H_p / L_p, cos_theta_s = H_s / L_s, cos_theta_d = H_d / L_d;
  Real p_r = data.p_a + data.g * data.rho * H_r, p_t = data.p_a + data.g * data.rho * H_t;
  Real Z_i = A_i / L_i, Z_p = A_p / L_p, Z_s = A_s * cos_theta_s / x3, Z_d = A_d / L_d;
  Real B_i = D_i / A_i ^ 2, B_p = D_p / A_p ^ 2, B_s = D_s / A_s ^ 2, B_d = D_d / A_d ^ 2;
  Real fD_i = fD, fD_p = fD, fD_s = fD, fD_d = fD;
  Real phat_tr1, phat_n, K_dp, K_p, K_z, K_pd;
  Real xhat_2(start = x_2, fixed = true), zhat_2, x2_real;
  Real L1u, L1l, L11;
equation
  u = if time < 100 then 0.7493 else 0.6493;
  //if time < 20.0 then 0.7493 else 0.7393;
  //hpmod.u = u;
  //x1 = hpmod.Vdot_p;
  //x3 = hpmod.h_s;
  //x2_real = hpmod.Vdot_s;
  //hpreal.u = u;
  //x1 = hpreal.turbine.V_dot;
  //x3 = hpreal.surgeTank.h;
  //x2_real = hpreal.surgeTank.V_dot;
  hprealkp.u = u;
  x1 = hprealkp.turbine.V_dot;
  x3 = hprealkp.surgeTank.h;
  x2_real = hprealkp.surgeTank.V_dot;
  K_dp = Z_d / (Z_d + Z_p);
  K_z = K_dp / Z_d;
  K_p = Z_i * Z_d / (Z_i * Z_d + Z_s * Z_d + Z_p * Z_d - Z_p ^ 2 * K_dp);
  K_pd = Z_p * K_dp / Z_d;
  xhat_2 = zhat_2 - L11 * x1 - L3 * x3;
  der(zhat_2) = A_s * cos_theta_s / data.rho / x3 * (phat_n - data.p_a) - A_s * data.g * cos_theta_s - 1 / 8 * pi * fD_s * B_s * xhat_2 * abs(xhat_2) + L11 * (Z_p / data.rho * (phat_n - phat_tr1) + A_p * data.g * cos_theta_p - 1 / 8 * pi * fD_p * B_p * x1 * abs(x1)) + L3 * (xhat_2 * cos_theta_s / A_s);
  phat_n = K_p / Z_i * (Z_i * p_r + Z_s * data.p_a + Z_p * K_dp * (x1 ^ 2 * data.p_a / (C_v ^ 2 * u ^ 2) + p_t) + data.rho * data.g * (A_p * cos_theta_p * (K_pd - 1) - K_pd * A_d * cos_theta_d + A_s * cos_theta_s + A_i * cos_theta_i) + 1 / 8 * pi * data.rho * (fD_s * B_s * xhat_2 * abs(xhat_2) + (fD_d * B_d * K_pd + fD_p * B_p * (1 - K_pd)) * x1 * abs(x1) - fD_i * B_i * (x1 + xhat_2) * abs(x1 + xhat_2)));
  phat_tr1 = K_z * (Z_p * phat_n + Z_d * (x1 ^ 2 * data.p_a / (C_v ^ 2 * u ^ 2) + p_t) + data.rho * data.g * (A_p * cos_theta_p - A_d * cos_theta_d) + 1 / 8 * pi * data.rho * x1 * abs(x1) * (fD_d * B_d - fD_p * B_p));
  L1u = A_s * cos_theta_s / x3 / Z_p / (1 - K_z * Z_p);
  L1l = L1u - Z_i / Z_p / K_p / (1 - K_z * Z_p);
  L11 = L1 + L1u * L1uweight;
end HPModelObservSim;
